module.exports = {
    Admin: require('./Admin.model'),
    Page: require('./Page.model'),
    User : require('./User.model'),
    Categories: require('./Categories.model'),
    AdminSettings : require('./Settings.model'),
    TempMobile : require('./TempMobile.model'),
    LikeDislike : require('./LikeDislike.model'),
    Country: require('./Country.model'),
    State: require('./State.model'),
    City: require('./City.model'),
    Location: require('./Location.model'),
    Rating : require('./Rating.model'),
    VisitRestaurant : require('./VisitRestaurant.model'),
    Restaurant : require('./Restaurant.model'),
    FavoriteRestaurant : require('./FavoriteRestaurant.model'),
    Zip : require('./Zip.model'),
    EmailNotifcation : require('./EmailNotification.model'),
    Faq : require('./Faq.model'),
    CustomerSaving : require('./CustomerSaving.model'),
    GuideLine:require('./GuideLine.model'),
    Restaurant:require('./Restaurant.model'),
    Location:require('./Location.model'),
    LikeDislike:require('./LikeDislike.model'),
    Rating:require('./Rating.model'),
    VisitRestaurant:require('./VisitRestaurant.model'),
    FavoriteRestaurant:require('./FavoriteRestaurant.model'),
    Setting:require('./Settings.model'),
	Food:require('./Food.model'),
    DupRestaurant: require('./DuplicateRestaurant.model'),
    EditRestaurant: require('./EditRestaurant.model'),
    Version: require('./version_settings.model'),
    AdminNotification : require('./AdminNotification.model'),
    Static: require('./Static.model'),
    Logyelp: require('./Logyelp.model')
};
